RIOT-OS/RobotFW-tests

tests/periph_i2c/tests/01__periph_i2c_base.robot

The tests are currently testing an undefined state
Any i2c action must be acquired
Currently the HiL is reporting errors in an undefined state.  RIOT does not guarantee the i2c state if unacquired, some cpus may work and some may not.  To make it consistent extra bytes are needed and unnecessary if the documentation is followed.

fix(i2c): Remove invalid i2c tests

---

tests/periph_i2c/tests/01__periph_i2c_base.robot

Since we must acquire before doing anything with the bus the test is wrong.  This should fix it and also fix the failing frdm-k22f board in the HiL
Fixes #3

fix(i2c): Add i2c acquire and release to NACK check

---

dist/robotframework/Makefile.include

Without the sort command, the robot files are invoked in arbitrary order.
Signed-off-by: Yegor Yefremov <yegorslists@googlemail.com>

Make: sort robot files

---

tests/periph_i2c/tests/01__periph_i2c_base.robot

A bug was found when multiple nacks due to read bytes were issued.
This test identifies this bug by reading the incorrect bytes
multiple times then trying to recover with read byte.

feature(i2c): Add read bytes nack test

---

dist/robotframework/lib/PhilipAPI.py
dist/robotframework/res/philip.keywords.txt
tests/periph_uart/tests/01__periph_uart_base.robot
tests/periph_uart/tests/02__periph_uart_mode.robot
tests/periph_uart/tests/periph_uart.keywords.txt
tests/periph_uart/tests/periph_uart_if.py
tests/periph_uart/tests/test_vars.py

Add support for new UART API call `uart_mode`.
Before performing these new tests, the DUT will be checked whether `uart_mode` is supported. If not, the test will be marked as **PASS** with a note "Feature is not supported".

Uart mode tests

---

dist/robotframework/README.md
dist/robotframework/requirements.txt
dist/robotframework/res/philip.keywords.txt
dist/robotframework/res/riot_base.keywords.txt
tests/periph_i2c/tests/01__periph_i2c_base.robot
tests/periph_i2c/tests/02__periph_i2c_write_register.robot
tests/periph_i2c/tests/03__periph_i2c_error_codes.robot
tests/periph_uart/tests/01__periph_uart_base.robot
tests/periph_uart/tests/02__periph_uart_mode.robot
tests/xtimer_cli/tests/01__xtimer_base.robot

This PR removes a special (Philip based) reset command and relies on `make reset` provided by RIOT which can be replaces by setting env variables if needed.
Also renames the other reset command to reflect that it uses RIOT.

tests: generalise reset keyword

---

tests/periph_uart/tests/01__periph_uart_base.robot
tests/periph_uart/tests/periph_uart_if.py

This commit switches philip initialization to the start which prevents philip init from providing unwanted bytes to the dut. It also clears the dut buffer by discarding a junk message.
This greatly improves reliability.
Run through tests with master and with this PR (on the samr21 or nucleo-l073) a few times to ensure initial byte errors are corrected.

tests/uart: improve robustness of uart tests

---

dist/robotframework/res/api_shell.keywords.txt
tests/periph_i2c/tests/01__periph_i2c_base.robot
tests/periph_i2c/tests/02__periph_i2c_write_register.robot
tests/periph_i2c/tests/03__periph_i2c_error_codes.robot
tests/periph_uart/main.c
tests/periph_uart/tests/01__periph_uart_base.robot
tests/periph_uart/tests/02__periph_uart_mode.robot
tests/periph_uart/tests/periph_uart.keywords.txt
tests/periph_uart/tests/periph_uart_if.py
tests/xtimer_cli/tests/01__xtimer_base.robot

This adapts the periph_uart test to use existing keywords and be consistent with other tests.

tests/periph_uart: full rework

---

tests/xtimer_cli/tests/Xtimer.py
tests/xtimer_cli/tests/xtimer_if.py

minor change to make robot framework integration of xtimer test consistent with the other tests.

tests/xtimer_cli: rework python integration

---

tests/Makefile.tests_common
tests/periph_i2c/tests/periph_i2c.keywords.txt
tests/periph_uart/tests/periph_uart.keywords.txt
tests/xtimer_cli/tests/01__xtimer_base.robot

this should improve (i.e. lower) overall test runtime

tests: make shell cmd timeout configurable

---

tests/Makefile.tests_common
tests/common/Makefile
tests/common/Makefile.include
tests/common/include/test_helpers.h
tests/common/test_helpers.c
tests/if_parser/Makefile
tests/if_parser/README.md
tests/if_parser/main.c

This adds a common test helpers module
The test helpers has a way to set human readable or json parsing
An app_metadata test is provided as an example
1. `BOARD=<board_of_your_choice> make flash term -C tests/if_parser`
2. Go through each command with in `help`
3. Everything should have json formatted results
4. Compile with `USE_JSON_SHELL_PARSER=0`
5. Check all commands again for human readable output

feat(parser): Add a json shell parser with example

---

tests/periph_i2c/main.c

Recently the I2C API in RIOT changed, so that i2c_release does not have a
return value anymore.
This is kind of urgent to fix our i2c tests

fix: adapt tests/periph_i2c to API change

---

tests/periph_gpio/Makefile
tests/periph_gpio/main.c
tests/periph_gpio/tests/01__periph_gpio_base.robot
tests/periph_gpio/tests/GPIOdevice.py
tests/periph_gpio/tests/periph_gpio.keywords.txt
tests/periph_gpio/tests/periph_gpio_if.py

This adds some firmware and interface for periph GPIO
It also has a robot test to check if the debug pins are correct
This can serve as a basis for other GPIO tests but is immediatly useful to test if the debug pins in a CI are correct.
This can be used in the future to check if the `gpio_init` can override pins initialized with af such as SPI and I2C pins.  PHiLIP must first be upgraded to read the values of each of the pins.
The gpio port can be written a number of ways which gets taken care of in the python interface.
```
PORT_A
PORTA
P_A
PA
P0
0
```
What I did:
`DEBUG0_PORT=P1 DEBUG0_PIN=5 DEBUG1_PORT=P_B DEBUG1_PIN=3 DEBUG2_PORT=PA DEBUG2_PIN=12 PHILIP_PORT=/dev/ttyACM1 PORT=/dev/ttyACM0 BOARD=nucleo-l433rc make robot-clean robot-test robot-html -C tests/periph_gpio/`
Generalized …

tests/periph_gpio: Add periph gpio test for debug pin checks

---

tests/periph_timer/tests/01__periph_timer_base.robot
tests/periph_timer/tests/02__periph_timer_extra.robot
tests/periph_timer/tests/03__periph_timer_set_delays.robot

The suite and test setup were different from the other tests. First they didn't reset philip all the time and also didn't use "RIOT Reset" for DUT. This is fixed here, that should resolve some weird errors we saw with some boards, e.g. remote-revb.

tests/periph_timer: fix resets in test setup

---

tests/common/test_helpers.c

Explicitly state print an int32 with PRId32 instead of %li.
Some MCUs have a different meaning for long int which causes compilation failure, most notably the ESP32.
compile any RF test for the `esp32-wroom-32` board.

tests/common/test_helpers: Fix printf casting

---

tests/periph_uart/Makefile
tests/periph_uart/tests/01__periph_uart_base.robot
tests/periph_uart/tests/02__periph_uart_mode.robot
tests/periph_uart/tests/periph_uart.keywords.txt
tests/periph_uart/tests/periph_uart_if.py

We should have a way to specify the device.  In the case of the `slstk3401a` the UART dev 1 pins are used by the SPI dev 0, with this we should be able to specify UART dev 2 for this board only.
Expose uart dev with the RF_UART_DEV environment variable
Add logging for the setup philip command
Align and clean tests
Remove unusable __main__ local test
Remove `BOARD_INSUFFICIENT_MEMORY`
Let the CI test

tests/periph_uart: Expose uart dev and clean

---

Jenkinsfile
dist/tools/ci/print_environment.py
dist/tools/ci/print_environment.sh

This PR adds a script to print out the environment variables, python packages being used, and the toolchains being used.  It also adds a call for Jenkins to print the information.
Call the `dist/tools/print_versions.sh` from different directories.
~Also read the CI output.~ <- Not included in the CI yet

dist/tools: Add tool to print current setup

---

dist/tools/ci/print_environment.sh

Fixes the script name from `print_python_versions` to `print_environment`.
Test by calling `print_environment.sh`

dist/tools/ci: Fix script naming for print env

---

tests/periph_timer/main.c

The esp32* seems to have some issues with bool type and what an unsigned long is.
Since bool types are being used, the stdbool is included.
Also since the port and pin type are defined as uint32_t, the call should be specifically for uint32_t.
`BOARD=esp32-wroom-32 make all -C tests/periph_timer`
It will fail in master and this PR fixes it.

fix(periph_timer): Fix casting issues in periph timer

---

tests/periph_timer/main.c

It seems some copy pasta issues with the `tests/periph_timer/main.c` file where it expects more arguments that is needed.
This PR fixes the argument checks for `cmd_timer_clear`, `cmd_timer_read`, `cmd_timer_start`, and `cmd_timer_stop`.
Let the CI test this one!

tests/periph_timer: Fix arg check of some timer calls

---

tests/periph_timer/main.c

It seems like the gpio pin is only taking the pin and not the proper `GPIO(PORT, PIN)`.
This fixes it.
Check to see if the CI is fixed.  The `nucleo-f103rb` is one board that suffers from this problem.

tests/timer:Fix gpio_init call in cmd_timer_debug_pin

---

README.md

First, after invoking the robot-clean target the user can rerun
the tests.

docs(README): mention robot-clean target

---

dist/robotframework/Makefile.include

This PR adds an option to the `robot.run` command to differentiate critical and non-critical tests in xUnit results.
Refer last paragraph: https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id747

robot: differentiate non-critical tests in xUnit results

---

Jenkinsfile

This PR experimentally adds `--depth 1` to the `git submodule update`. The objective is to reduce the network overhead that comes with downloading the huge history of the RIOT submodule.
Let's observe this first, before merging.
EDIT: I added another commit that replaces the github interaction for each executor with a proper stash/unstash. The master node is now performing the initial `git clone` and scm setup, stashes the working dir, and all executors unstash the working directory.

Jenkinsfile: Pipeline improvements to speed up source code checkout

---

tests/periph_spi/main.c
tests/periph_spi/tests/01__periph_spi_base.robot
tests/periph_spi/tests/02__periph_spi_transfer.robot
tests/periph_spi/tests/03__periph_spi_modes.robot
tests/periph_spi/tests/periph_spi.keywords.txt
tests/periph_spi/tests/periph_spi_if.py
tests/periph_spi/tests/test_vars.py

This PR fixes some bugs in the interface and the main program of the SPI and extends the tests as follows:
- All 4 modes (different variations of the clk phase and clk polarity) are tested now.
- The transfer of bytes is tested with all possible functions of the interface
- A test for double acquiring the SPI bus. 
This was tested with the boards:
- nucleo-l073rz
- nucleo-f303re
- nucleo-l152re
and nucleo-f103rb as PHiLIP-board.

periph_spi: Add extension of SPI tests

---

Jenkinsfile

It appears that the current stash and unstash has some issues with asynchronous behaviour. For example an unstash occurs on a node in a working directory that is different than what is expected when running a test. It also appears that some directories are not being cleaned.
The following PR makes a number of changes to fix that:
- makes jenkinsfile declarative as this is better supported
- run all tests on node before releasing to fix any shared workspace  problems
- Cleanup function names and steps to make it more readable
- Add timeouts to overall process of 1 hour and per node at 45 mins
- Handle errors if unstash fails only stop the node
Check the CI, I don't know how that params will effect everything but it is better than now and we can always fix later if an issue occurs
Checks …

fix(Jenkinsfile): Fix jenkins pipline for CI

---

dist/robotframework/res/api_shell.keywords.txt

It seems like updating robot has some deprecation issues.
The warning  appears `Error in file '/opt/jenkins/workspace/RIOT-HIL_nightly/dist/robotframework/res/api_shell.keywords.txt' in FOR loop starting on line 59: For loop header ':FOR' is deprecated. Use 'FOR' instead.`
This fixes that by using `FOR` instead of `:FOR`.

api_shell: Fix FOR warning

---

Jenkinsfile

It seems that the trigger apply to every branch causing really long build times.
This should only run nightly and not all branches.

Jenkinsfile: Only run nightlies every night

---

Jenkinsfile

It seems that the trigger apply to every branch causing really long build times.
This should only run nightly and not all branches.
This is a workaround since declarative pipeline do not allow for conditional triggers so the script functionality must be called.
It starts a cron job to build at 1am every morning with RIOT master.

Jenkinsfile: Conditional trigger for nightlies

---

tests/periph_gpio/tests/02__periph_gpio_others.robot

Now that the environment for the PWM and IC pins are defined we should start testing to make sure they are connected.
This should be verified in the CI. At least a few boards should have this functioning (the ones that don't need to be rewired).

tests/periph_gpio: Add IC and PWM to gpio test

---

.gitignore
dist/robotframework/res/util.keywords.txt
dist/tools/output_to_xunit/README.md
dist/tools/output_to_xunit/output_to_xunit.py
dist/tools/output_to_xunit/test/TestData.py
dist/tools/output_to_xunit/test/example_testsuite/example_test.robot

This PR adds the keyword "Record Property" and also a parser script `output_to_xunit.py` parser script to parse the of RobotFrameworks `output.xml`. The parsed xUnit is same as the xUnit output of RF (`--xunit xunit.xm` and `--xunitskipnoncritical`), with the addition of `<properties>` tag to record the properties.
NOTE: The parser script is limited to handle only the current structure of testsuites/testcases. It may produce incorrect xUnit output when used on other `output.xml`.
To use the keyword, include `utils.keyword.txt` as a `Resource` in the `.robot` file. See `dist/tools/output_to_xunit/test/example_testsuite/example_test.robot` for example.

Add "Record Property" keyword

---

dist/robotframework/Makefile.include
dist/tools/output_to_xunit/output_to_xunit.py
dist/tools/output_to_xunit/test/example_testsuite/example_test.robot

This PR changes the build system to use the `output_to_xunit.py` script from #75. The script is also changed to detect Record Property tags in nested deeper in the output, making the parsing more robust. The `robot-test` command is modified to specify only the top directory of the RF tests e.g. (`tests/`) to make sure that the resulting `output.xml` maintains the directory structure that we defined.
Run the instruction in the README. In the resulting `test_xunit.xml` a new testcase `Record using keyword` is added.
Expected:
```
<testcase classname="Example Testsuite.Example Test" name="Record using keyword" time="0.002">
<properties>
<property name="LONG_STRING" value="LSSDDDJDLJFLJSFDEJSYKLSLSDSKLSDEJFJKYDKJKJHYLDEFDDJDHSHESLDLJJFKKJFKLKDLJDJKEKJDLHSHSJKJKYLJDDDSEYHKSSSJYLDDKFDDKSDSKKDKDS …
```

Use output xunit script

---

tests/periph_i2c/tests/01__periph_i2c_base.robot

Add a test in response to https://github.com/RIOT-OS/RIOT/issues/10269
This adds a test the acquires and releases then checks the SDA and SCL lines.
Just check the CI

periph_i2c: Add test for checking lines after release

---

tests/periph_spi/main.c
tests/periph_spi/tests/04__periph_spi_timer.robot
tests/periph_spi/tests/test_vars.py

This verifies the SPI Clock speed for the valid RIOT values of 100kHZ, 400kHz, 1MHz, 5MHz and 10MHz.
Also fixes a bug in the periph_spi main: the argument values were not mapped to the correct clock values.
Atleast for STM32 CPUs there are some problems with higher speeds and the transfer of multiple bytes since there is a pause with every byte. This is currently not calculated in the window and therefore the tranfer seems too slow.
For 10MHz and transfer ob Byte PHiLIP always gives 0 as spi.byte_ticks.

tests/periph_spi: Add tests for clock speed

---

tests/periph_uart/tests/periph_uart.keywords.txt

This allows the tests that do not support uart mode config to fail non-critically which shows a skip in the ci.  Similar to the GPIO tests.

fix(periph_uart): Make the missing uart modes skip and not pass

---

tests/periph_uart/Makefile

With this condition the uart test is only build if a uart device was specified in the environment of the board. If the HIL_UART_DEV is left blank the build fails with the given message.
This avoids that the test is build for boards that can't run it.

periph_uart/Makefile: Add condition to build only if a uart device is specified

---

Jenkinsfile
dist/tools/ci/env_parser.py

This updates the print environment script to run on older versions of python (the versions that are on the pi).
It also changes the Jenkins file to run the `results_to_xml.sh` script on the archived results producing a `metadata.xml` and compiling the xunit and metadata results into the `robot.xml`.

JenkinsFile: Compile xunit results into robot.xml

---

Jenkinsfile

This PR modifies the Jenkinsfile to also archive benchmark plots that will be generated by dist/tools/plot/plot_timer_benchmark.py from #82. It is split from that PR for easier testing.
*Same as #84 but using upstream branch*

Jenkinsfile: archive generated timer benchmarks plots

---

Jenkinsfile

The `-j` parameter that speeds up make by using all CPUs are not passed to the into docker when trying to make.
This fixes it.

Jenkinsfile: Speedup default jenkins build

---

Jenkinsfile

Current HIL_TESTS and HIL_BOARDS must not include any whitespace between the item list e.g. `samr21-xpro,saml10-xpro`. If the user adds whitespace between the comma and the next item in the list, the pipeline will interpret the whitespace as part of the item name.
This caused archiving artifacts steps failed because it cannot find tests with the whitespace name in it. Here is a excerpt of failure from [a pipeline run](https://ci.riot-os.org/hil/blue/organizations/jenkins/RIOT-HIL/detail/PR-90/16/pipeline/490):
```
Archiving artifacts
‘build/robot/arduino-due/ tests_ztimer_benchmarks/*.xml’ doesn’t match anything: ‘build’ exists but not ‘build/robot/arduino-due/ tests_ztimer_benchmarks/*.xml’
No artifacts found that match the file pattern "build/robot/arduino-due/ …
```

Jenkinsfile: remove whitespace before tokenizing board and test list

---

dist/robotframework/Makefile.include
dist/tools/output_to_xunit/README.md
dist/tools/output_to_xunit/output_to_xunit.py
dist/tools/output_to_xunit/test/example_testsuite/example_test.robot
tests/periph_gpio/tests/periph_gpio.keywords.txt
tests/periph_uart/tests/periph_uart.keywords.txt

The current "skip" tag are used to mark a failing test that are not fatal to the test suite. However, this can confuse user that the test are skipped/not run at all. This PR renames the "skip" tag to "non-critical" in the RF files and also the `output_to_xunit.py` script.
For `output_to_xunit.py`, there is a test RF suite that can be use. Follow the testing instruction in the README there. The final xunit.xml should have one  test case marked as skipped.
For the changes to RF files, let the HIL CI run through the test. The result should be the same as the nightlies.

dist/, tests/: rename "skip" tag to "non-critical"

---

dist/robotframework/res/api_shell.keywords.txt
tests/xtimer_benchmarks/Makefile
tests/xtimer_benchmarks/README.md
tests/xtimer_benchmarks/main.c
tests/xtimer_benchmarks/tests/00__timer_version.robot
tests/xtimer_benchmarks/tests/01__timer_overhead.robot
tests/xtimer_benchmarks/tests/02__sleep_accuracy.robot
tests/xtimer_benchmarks/tests/03__sleep_jitter.robot
tests/xtimer_benchmarks/tests/04__drift.robot.skip
tests/xtimer_benchmarks/tests/DutDeviceIf.py
tests/ztimer_benchmarks/Makefile
tests/ztimer_benchmarks/README.md
tests/ztimer_benchmarks/main.c
tests/ztimer_benchmarks/tests

This PR adds two new testsuites one for xtimer and ztimer with the timer benchmarks. This also adds plotting script for the results of the benchmark and outputs it into the `includes` folder in the results directory.
There are some helper functions in `DutDeviceIf.py` (`filter_trace`, `compress_result`) which translate the output format from `print_result` to a more friendlier format to work with.

Add timer benchmarks

---

dist/robotframework/Makefile.include
dist/tools/plot/plot_timer_benchmarks.py
dist/tools/plot/requirements.txt

This PR adds the plotting script for accuracy timer benchmarks. I also included the fix to the resulting HTML file to convert `<br>` tags in the Plotly output to `<br />`.
This script is only for the accuracy timer benchmark, for now, more coming.

Add plotting script for accuracy timer benchmark

---

tests/xtimer_benchmarks/main.c

On the z1 a warning is thrown during building`error: 'memset' used with length equal to number of elements without multiplication by element size [-Werror=memset-elt-size]`.
Since the full array is available we can just set it directly.
Note that this now zeros all `jitter_wakeups` (currently 100 elements).
Previously it was a hardcoded 25 elements.

tests/xtimer_benchmark: Use sizeof(array) in memset

---

dist/tools/ci/results_to_xml.sh

The old robot.xsl stylesheet is still included in the current xml result files but is no longer needed and can be safely removed.

Remove relation to deprecated XSL-Stylesheet in results_to_xml.sh

---

README.md
dist/robotframework/Makefile.include

Add ROBOT_EXTRA_ARGS env variable to have control over robot args.
This allows things like specific test selection when running.
The ROBOT_ARGS will remain the same and only add args to the default call.
Note that setting ROBOT_ARGS will no longer include ROBOT_EXTRA_ARGS.
A plain build should remain the same
```
make robot-clean robot-test -C dist/tools/output_to_xunit/
```
<details>
```
make: Entering directory '/home/weiss/wd/RobotFW-tests/dist/tools/output_to_xunit'
python3 -m robot.run \
--name "example" --settag "APP_example" --settag "BOARD_host" --metadata RIOT-Version: --metadata RIOT-Board:host --metadata RIOT-Application:example -P "/tests:/home/weiss/wd/RobotFW-tests/dist/tools/output_to_xunit/../../../dist/robotframework/lib:/home/weiss/wd/RobotFW-tests/dist/tools/output_to_xu …
```

dist/robotframework: Expose ROBOT_EXTRA_ARGS in build system

---

tests/periph_spi/main.c

spi_acquire() was changed to a void function with https://github.com/RIOT-OS/RIOT/pull/15902 
This adapts to these changes and the spi tests are able be build again.

periph_spi/main.c: Adapt to recent RIOT changes of spi_acquire()

---

dist/tools/output_to_xunit/output_to_xunit.py

It also allows for the exit code of `make robot-test` to return the amount of failed tests thus allowing the CI to properly indicate failures.
This is useful for the comment on PR...

output_to_xml: Fix return code of robot-test

---

tests/periph_spi/tests/04__periph_spi_timer.robot
tests/periph_spi/tests/test_vars.py

This introduces the following changes:
- Tests where the time is off limits but are otherwise successful are no longer failing but give a warning instead. 
- The 1 Byte tests were changed to 2 Bytes since there were problems with 1 Byte and 10MHz which always resulted in a measurement of 0.0us
- The measured times as well as the upper and lower limits are now logged to the xunit.xml
- Improved readability

tests/periph_spi: Improve timer tests

---

tests/periph_i2c/main.c

The RIOT API changed... This means that the test must be adapted...

tests/periph_i2c: Fix acquire api

---

tests/periph_spi/tests/04__periph_spi_timer.robot
tests/periph_spi/tests/test_vars.py

With updated PHiLIP 1.3.0 there are now functionalities to evaluate the measured clk speed more accurate by making use of captured timestamps of the SPI CLK pin and filtering dead times between bytes.
This measurement can only support speeds up to 5MHz therefore the tests were adapted and the 10MHz tests were removed.

SPI clk speed tests with PHiLIP 1.3.0
